pipeline {
    agent any

    stages {
        
        stage('Starting Cluster'){
            steps{

                    withCredentials([file(credentialsId: 'Jenkins-admin-sa', variable: 'GOOGLE_APPLICATION_CREDENTIAL')]) {
                
                     bat """
                            @echo OFF
                            gcloud config set project dollar-tree-project-369709
                            gcloud auth activate-service-account --key-file %GOOGLE_APPLICATION_CREDENTIAL%
                         """
                    }                     
                     wrap([$class: 'BuildUser']) {
                        
                        bat """
                        setlocal ENABLEDELAYEDEXPANSION
                        
                        @echo OFF
                       
                        gcloud -q dataproc clusters start dollar-tree-%BUILD_USER_ID% --region us-west1 
                        """
                     }
                    
                    
                }   
                post{
                   
                   success{
                    script {
               
                    emailext subject: 'Build Successful',
                        body: '<h3><b>Cluster has started.</b></h3>',
                        recipientProviders: [
                            [$class: 'CulpritsRecipientProvider'],
                            [$class: 'DevelopersRecipientProvider'],
                            [$class: 'RequesterRecipientProvider']
                        ], 
                        replyTo: '$DEFAULT_REPLYTO',
                        to: '$DEFAULT_RECIPIENTS'
                }
                   }
                failure{
                    script {
               
                    emailext subject: 'Build Failed',
                        body: '<h3><b>Cluster could not be started. It is possible that cluster does not exists, please check the jenkins console log.</b></h3>',
                        recipientProviders: [
                            [$class: 'CulpritsRecipientProvider'],
                            [$class: 'DevelopersRecipientProvider'],
                            [$class: 'RequesterRecipientProvider']
                        ], 
                        replyTo: '$DEFAULT_REPLYTO',
                        to: '$DEFAULT_RECIPIENTS'
                }


                }
        }
        }
    }
}
